[2023-08-11 17:40:01,629: INFO: main: Welcome]
[2023-08-15 11:58:39,225: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-15 11:58:39,256: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-15 11:58:39,256: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-15 11:58:39,272: INFO: common: created directory at: artifacts]
[2023-08-15 11:58:39,272: INFO: common: created directory at: artifacts/data_ingestion]
[2023-08-15 11:58:51,612: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-15 12:02:42,951: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-15 12:02:42,951: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-15 12:02:42,951: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-15 12:02:42,982: INFO: common: created directory at: artifacts]
[2023-08-15 12:02:42,982: INFO: common: created directory at: artifacts/data_ingestion]
[2023-08-15 12:02:53,059: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-18 16:54:25,571: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-18 16:54:25,603: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-18 16:54:25,603: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-18 16:54:25,618: INFO: common: created directory at: artifacts]
[2023-08-18 16:54:25,618: INFO: common: created directory at: artifacts/data_ingestion]
[2023-08-18 16:54:35,449: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-18 16:54:35,449: INFO: main: *******************]
[2023-08-18 16:54:35,449: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-18 16:54:35,449: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-18 16:54:35,464: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-18 16:54:35,464: INFO: common: created directory at: artifacts]
[2023-08-18 16:54:35,464: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-08-18 16:54:35,464: ERROR: main: 'ConfigurationManager' object has no attribute 'params']
Traceback (most recent call last):
  File "D:\Satyam Projects\Human-Emotion-Detection\main.py", line 20, in <module>
    prepare_base_model.main()
  File "d:\satyam projects\human-emotion-detection\src\humanEmotionClassifier\pipeline\stage_02_prepare_base_model.py", line 14, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\satyam projects\human-emotion-detection\src\humanEmotionClassifier\config\configuration.py", line 31, in get_prepare_base_model_config
    params_image_size=self.params.IMAGE_SIZE,
                      ^^^^^^^^^^^
AttributeError: 'ConfigurationManager' object has no attribute 'params'
[2023-08-18 16:58:20,911: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-18 16:58:20,911: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-18 16:58:20,927: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-18 16:58:20,927: INFO: common: created directory at: artifacts]
[2023-08-18 16:58:20,927: INFO: common: created directory at: artifacts/data_ingestion]
[2023-08-18 16:58:28,710: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-18 16:58:28,710: INFO: main: *******************]
[2023-08-18 16:58:28,710: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-18 16:58:28,710: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-18 16:58:28,710: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-18 16:58:28,710: INFO: common: created directory at: artifacts]
[2023-08-18 16:58:28,710: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-08-18 16:58:36,603: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-08-18 16:58:43,087: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-08-23 17:14:03,654: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-23 17:14:03,670: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-23 17:14:03,685: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-23 17:14:03,701: INFO: common: created directory at: artifacts]
[2023-08-23 17:14:03,701: INFO: common: created directory at: artifacts/data_ingestion]
[2023-08-23 17:14:13,338: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-23 17:14:13,338: INFO: main: *******************]
[2023-08-23 17:14:13,354: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-23 17:14:13,354: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-23 17:14:13,354: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-23 17:14:13,354: INFO: common: created directory at: artifacts]
[2023-08-23 17:14:13,448: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-08-23 17:14:20,794: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-08-23 17:14:26,699: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-08-23 17:14:26,699: INFO: main: *******************]
[2023-08-23 17:14:26,699: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-08-23 17:14:26,715: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-23 17:14:26,715: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-23 17:14:26,715: INFO: common: created directory at: artifacts]
[2023-08-23 17:14:26,825: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-08-23 17:14:26,825: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-08-23 17:14:26,857: ERROR: main: 'WindowsPath' object has no attribute 'endswith']
Traceback (most recent call last):
  File "D:\Satyam Projects\Human-Emotion-Detection\main.py", line 32, in <module>
    model_trainer.main()
  File "d:\satyam projects\human-emotion-detection\src\humanEmotionClassifier\pipeline\stage_03_training.py", line 19, in main
    callback_list = prepare_callbacks.get_tb_ckpt_callbacks()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\satyam projects\human-emotion-detection\src\humanEmotionClassifier\components\prepare_callbacks.py", line 32, in get_tb_ckpt_callbacks
    self._create_ckpt_callbacks
  File "d:\satyam projects\human-emotion-detection\src\humanEmotionClassifier\components\prepare_callbacks.py", line 23, in _create_ckpt_callbacks
    return tf.keras.callbacks.ModelCheckpoint(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\humanEmotion\Lib\site-packages\keras\src\callbacks.py", line 1369, in __init__
    if filepath and filepath.endswith(".keras") and options is not None:
                    ^^^^^^^^^^^^^^^^^
AttributeError: 'WindowsPath' object has no attribute 'endswith'
[2023-08-23 17:16:46,996: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-23 17:16:46,996: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-23 17:16:47,011: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-23 17:16:47,011: INFO: common: created directory at: artifacts]
[2023-08-23 17:16:47,028: INFO: common: created directory at: artifacts/data_ingestion]
[2023-08-23 17:16:56,035: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-23 17:16:56,035: INFO: main: *******************]
[2023-08-23 17:16:56,035: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-23 17:16:56,041: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-23 17:16:56,051: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-23 17:16:56,051: INFO: common: created directory at: artifacts]
[2023-08-23 17:16:56,051: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-08-23 17:17:01,438: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-08-23 17:17:05,789: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-08-23 17:17:05,789: INFO: main: *******************]
[2023-08-23 17:17:05,789: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-08-23 17:17:05,805: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-23 17:17:05,805: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-23 17:17:05,805: INFO: common: created directory at: artifacts]
[2023-08-23 17:17:05,805: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-08-23 17:17:05,883: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-08-23 17:17:06,009: INFO: common: created directory at: artifacts\training]
[2023-08-23 17:23:46,538: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-08-26 16:34:43,885: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-26 16:34:43,900: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-26 16:34:43,900: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-26 16:34:43,900: INFO: common: created directory at: artifacts]
[2023-08-26 16:34:43,900: INFO: common: created directory at: artifacts/data_ingestion]
[2023-08-26 16:34:51,232: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-26 16:34:51,232: INFO: main: *******************]
[2023-08-26 16:34:51,232: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-26 16:34:51,247: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-26 16:34:51,247: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-26 16:34:51,247: INFO: common: created directory at: artifacts]
[2023-08-26 16:34:51,247: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-08-26 16:34:57,078: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-08-26 16:35:01,831: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-08-26 16:35:01,831: INFO: main: *******************]
[2023-08-26 16:35:01,831: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-08-26 16:35:01,831: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-26 16:35:01,831: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-26 16:35:01,831: INFO: common: created directory at: artifacts]
[2023-08-26 16:35:02,003: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-08-26 16:35:02,003: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-08-26 16:35:02,034: INFO: common: created directory at: artifacts\training]
[2023-08-26 16:41:02,570: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-08-26 17:00:33,524: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-26 17:00:33,540: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-26 17:00:33,540: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-26 17:00:33,540: INFO: common: created directory at: artifacts]
[2023-08-26 17:00:33,555: INFO: common: created directory at: artifacts/data_ingestion]
[2023-08-26 17:00:40,492: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-26 17:00:40,492: INFO: main: *******************]
[2023-08-26 17:00:40,492: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-26 17:00:40,508: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-26 17:00:40,508: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-26 17:00:40,508: INFO: common: created directory at: artifacts]
[2023-08-26 17:00:40,508: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-08-26 17:00:40,508: ERROR: main: "'ConfigBox' object has no attribute 'image_size'"]
Traceback (most recent call last):
  File "D:\Anaconda\envs\humanEmotion\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'IMAGE_SIZE'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Anaconda\envs\humanEmotion\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\humanEmotion\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'IMAGE_SIZE'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\humanEmotion\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'IMAGE_SIZE'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Anaconda\envs\humanEmotion\Lib\site-packages\box\config_box.py", line 28, in __getattr__
    return super().__getattr__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\humanEmotion\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'IMAGE_SIZE'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\humanEmotion\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'image_size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Anaconda\envs\humanEmotion\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\humanEmotion\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'image_size'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\humanEmotion\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'image_size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Satyam Projects\Human-Emotion-Detection\main.py", line 21, in <module>
    prepare_base_model.main()
  File "d:\satyam projects\human-emotion-detection\src\humanEmotionClassifier\pipeline\stage_02_prepare_base_model.py", line 14, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\satyam projects\human-emotion-detection\src\humanEmotionClassifier\config\configuration.py", line 32, in get_prepare_base_model_config
    params_image_size=self.params.IMAGE_SIZE,
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\humanEmotion\Lib\site-packages\box\config_box.py", line 30, in __getattr__
    return super().__getattr__(item.lower())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\humanEmotion\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'image_size'"
[2023-08-26 17:01:36,292: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-26 17:01:36,292: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-26 17:01:36,292: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-26 17:01:36,292: INFO: common: created directory at: artifacts]
[2023-08-26 17:01:36,292: INFO: common: created directory at: artifacts/data_ingestion]
[2023-08-26 17:01:43,072: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-26 17:01:43,072: INFO: main: *******************]
[2023-08-26 17:01:43,072: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-26 17:01:43,072: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-26 17:01:43,072: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-26 17:01:43,072: INFO: common: created directory at: artifacts]
[2023-08-26 17:01:43,072: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-08-26 17:01:43,072: ERROR: main: If using `weights` as `"imagenet"` with `include_top` as true, `classes` should be 1000]
Traceback (most recent call last):
  File "D:\Satyam Projects\Human-Emotion-Detection\main.py", line 21, in <module>
    prepare_base_model.main()
  File "d:\satyam projects\human-emotion-detection\src\humanEmotionClassifier\pipeline\stage_02_prepare_base_model.py", line 16, in main
    prepare_base_model.get_base_model()
  File "d:\satyam projects\human-emotion-detection\src\humanEmotionClassifier\components\prepare_base_model.py", line 14, in get_base_model
    self.model = tf.keras.applications.xception.Xception(include_top=self.config.params_include_top,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\humanEmotion\Lib\site-packages\keras\src\applications\xception.py", line 130, in Xception
    raise ValueError(
ValueError: If using `weights` as `"imagenet"` with `include_top` as true, `classes` should be 1000
[2023-08-26 17:03:21,108: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-26 17:03:21,108: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-26 17:03:21,108: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-26 17:03:21,155: INFO: common: created directory at: artifacts]
[2023-08-26 17:03:21,155: INFO: common: created directory at: artifacts/data_ingestion]
[2023-08-26 17:03:27,190: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-26 17:03:27,190: INFO: main: *******************]
[2023-08-26 17:03:27,190: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-26 17:03:27,190: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-26 17:03:27,190: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-26 17:03:27,190: INFO: common: created directory at: artifacts]
[2023-08-26 17:03:27,190: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-08-26 17:03:27,190: ERROR: main: "'ConfigBox' object has no attribute 'classes'"]
Traceback (most recent call last):
  File "D:\Anaconda\envs\humanEmotion\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'CLASSES'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Anaconda\envs\humanEmotion\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\humanEmotion\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'CLASSES'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\humanEmotion\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'CLASSES'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Anaconda\envs\humanEmotion\Lib\site-packages\box\config_box.py", line 28, in __getattr__
    return super().__getattr__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\humanEmotion\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'CLASSES'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\humanEmotion\Lib\site-packages\box\box.py", line 503, in __getitem__
    return super().__getitem__(item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'classes'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Anaconda\envs\humanEmotion\Lib\site-packages\box\box.py", line 536, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\humanEmotion\Lib\site-packages\box\box.py", line 524, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'classes'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\humanEmotion\Lib\site-packages\box\box.py", line 538, in __getattr__
    value = object.__getattribute__(self, item)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigBox' object has no attribute 'classes'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Satyam Projects\Human-Emotion-Detection\main.py", line 21, in <module>
    prepare_base_model.main()
  File "d:\satyam projects\human-emotion-detection\src\humanEmotionClassifier\pipeline\stage_02_prepare_base_model.py", line 14, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\satyam projects\human-emotion-detection\src\humanEmotionClassifier\config\configuration.py", line 36, in get_prepare_base_model_config
    params_classes=self.params.CLASSES
                   ^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\humanEmotion\Lib\site-packages\box\config_box.py", line 30, in __getattr__
    return super().__getattr__(item.lower())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\humanEmotion\Lib\site-packages\box\box.py", line 552, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'classes'"
[2023-08-26 17:04:07,559: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-26 17:04:07,559: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-26 17:04:07,559: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-26 17:04:07,559: INFO: common: created directory at: artifacts]
[2023-08-26 17:04:07,559: INFO: common: created directory at: artifacts/data_ingestion]
[2023-08-26 17:04:14,217: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-26 17:04:14,217: INFO: main: *******************]
[2023-08-26 17:04:14,217: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-26 17:04:14,233: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-26 17:04:14,233: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-26 17:04:14,233: INFO: common: created directory at: artifacts]
[2023-08-26 17:04:14,233: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-08-26 17:04:23,379: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-08-26 17:04:30,053: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-08-26 17:04:30,053: INFO: main: *******************]
[2023-08-26 17:04:30,053: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-08-26 17:04:30,053: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-26 17:04:30,053: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-26 17:04:30,053: INFO: common: created directory at: artifacts]
[2023-08-26 17:04:30,131: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-08-26 17:04:30,131: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-08-26 17:04:30,147: INFO: common: created directory at: artifacts\training]
[2023-08-26 17:10:22,458: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-08-26 18:00:38,443: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-26 18:00:38,459: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-26 18:00:38,459: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-26 18:00:38,459: INFO: common: created directory at: artifacts]
[2023-08-26 18:00:38,474: INFO: common: created directory at: artifacts/data_ingestion]
[2023-08-26 18:00:46,338: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-26 18:00:46,338: INFO: main: *******************]
[2023-08-26 18:00:46,338: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-26 18:00:46,338: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-26 18:00:46,338: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-26 18:00:46,338: INFO: common: created directory at: artifacts]
[2023-08-26 18:00:46,338: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-08-26 18:00:51,235: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-08-26 18:00:54,596: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-08-26 18:00:54,596: INFO: main: *******************]
[2023-08-26 18:00:54,596: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-08-26 18:00:54,596: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-26 18:00:54,596: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-26 18:00:54,596: INFO: common: created directory at: artifacts]
[2023-08-26 18:00:54,611: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-08-26 18:00:54,737: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-08-26 18:00:54,753: INFO: common: created directory at: artifacts\training]
[2023-08-26 18:09:23,645: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-08-26 18:13:01,937: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2023-08-26 18:13:01,952: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-26 18:13:01,952: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-26 18:13:01,968: INFO: common: created directory at: artifacts]
[2023-08-26 18:13:01,968: INFO: common: created directory at: artifacts/data_ingestion]
[2023-08-26 18:13:08,795: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2023-08-26 18:13:08,798: INFO: main: *******************]
[2023-08-26 18:13:08,798: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2023-08-26 18:13:08,798: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-26 18:13:08,798: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-26 18:13:08,798: INFO: common: created directory at: artifacts]
[2023-08-26 18:13:08,798: INFO: common: created directory at: artifacts/prepare_base_model]
[2023-08-26 18:13:11,935: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2023-08-26 18:13:14,526: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2023-08-26 18:13:14,526: INFO: main: *******************]
[2023-08-26 18:13:14,526: INFO: main: >>>>>> stage Training started <<<<<<]
[2023-08-26 18:13:14,541: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-26 18:13:14,541: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-26 18:13:14,541: INFO: common: created directory at: artifacts]
[2023-08-26 18:13:14,730: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2023-08-26 18:13:14,745: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2023-08-26 18:13:14,745: INFO: common: created directory at: artifacts\training]
[2023-08-26 18:20:56,856: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2023-08-26 18:20:56,856: INFO: main: *******************]
[2023-08-26 18:20:56,856: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2023-08-26 18:20:56,856: INFO: common: yaml file: config\config.yaml loaded successfully]
[2023-08-26 18:20:56,872: INFO: common: yaml file: params.yaml loaded successfully]
[2023-08-26 18:20:56,872: INFO: common: created directory at: artifacts]
[2023-08-26 18:21:08,738: INFO: common: json file saved at: scores.json]
[2023-08-26 18:21:08,738: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
